# Generated by Django 4.0 on 2022-02-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('passID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('stationRef', models.CharField(max_length=255)),
                ('vehicleRef', models.CharField(max_length=255)),
                ('charge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stationProvider', models.CharField(max_length=255)),
                ('stationName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tagID', models.CharField(max_length=255)),
                ('tagProvider', models.CharField(max_length=255)),
                ('providerAbbr', models.CharField(max_length=255)),
                ('licenseYear', models.IntegerField()),
            ],
        ),
    ]
